### ISSUE TITLE
Style - Foreground / Background

### ISSUE THREAD

**Issue by EricZimmermann** [EricZimmermann/McHacks-2022#7]
Generic nerual style transfer
User may select form a few preset styles, option to upload style
Toggle (on, off, foreground, background)

One shot face stylization (TBD)
JOJOGAN / ARCANE ETC
(https://github.com/mchong6/JoJoGAN)

**Comment by JustinSzeto** [comment]
JoJoGAN doesn't work for now. Requires local CUDA installation to load some fused CUDA ops
